language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest-cov
install:
  - pip install .
# command to run tests
script:
  - pytest
after_success:
  coveralls
deploy:
  provider: pypi
  user: "thibdct"
  password:
    secure: "hcma42E/pq5Ixr/V4KUZ0CtkCkpaeldGgiLuSoQOzRaQRjOgPbMud0VNrXcIrl2tB+qiw51fgcti9oQrzogbzJuMEXToPnR8RP3zPdZUmpg8c9usgqIwmplhXj7bNibfQJhxwl0r1gprNbuKlfXrNcLM2uaqHWGCeKCwO+JW7gzIv4Cb9uu6v1mTfhyR/EnTZHzLoqUHgj7dNbLUKTypjT8dfQakhFT3bsJfCTg8gJDvcfdth9r0eFiwnopVbPsXO2OwbMuDuv17T+7ykNfXAL8Q/1HhnUTIIr9ptEBq8CH0aD/+/hzUl3l/69KukyEPn5CtQivLfVtiB4pw3UK/1xMqb70iSugq441lHzwdmqmpg2p5OXT+WDtiuWPUkhezJcu8/irUTk7Iq0DXMKUASbVHSIuH10FILos4P8Og5pF9+2Zzo+rZcENVpDaeBCQ7Lx0KVN6fZzm2Xe5r4JiJWjrQzmzMS71oWu2PbLh0/G+kaZw3DSsAd0VEyu/qcyzmAegdJVo021tdgw/6mmcYUZIp4jYqUsT8KJfInAnBei9NyAOYFIbL+D/RkOBHGjODO44zgCYHPNutKlyW2JbYJ0F48lcuRGBuXDxeqsS8UaWPrCuHDWx0Wp1BNIiifp41TmzHZ/+5Dw9Fl5uZr+Ved3n8tCZqamMgCf+7lVRo5zo="
  on:
    tags: true