language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install pytest-cov
install:
  - pip install .
# command to run tests
script:
  - pytest
after_success:
  coveralls
deploy:
  provider: pypi
  user: "thibdct"
  password:
    secure: "3MySEWHjOw9JmIgmxT/F84Jaxokcka88lWfAQ3TguKn6Rys3gstk24VqW3NiCeCfOnSAP55wPaqY/iD5DWHqshhq8b+/FXUTd0XWP7rQy33ooyH5hSsmSCzMBdREH80cmXTonV3G4NWMqy+arEwI/pqdxGpmFTSs7usTpZTdJHfEIBBZVK/IJ+pbAyBXdmALTpZmUizpSQLtPlu+eDfbt/YHW8l4M1BU5JbnUKrP64K1zSjPZVOVoRudNVc8QXmoWdoaK8GKcS1uQ9Rbb4NngkhSmI5hbOPGB49swmG+197+OwY6u8hT28N0icFfqHLXXV2ert8hiFb548PVtjbFV7A34FCUhhKaMqwQzEdy9HzLdWIYeBqhJlEYLEXxOUXV2tmgOuPemQuUdFJBy3p4C7C7M01H0HZENC9idm05d0CA1ZFhmWMN3+i6UNqgsRLqsxO7MeHyHVUQ/Otiu+N2hr1On1ub3BzhyY4UM8AhGm8VWBJypfxRhs2gaGil6QLhWOMuxUsi6jDO1p1LekbFSoeg/YF70jTreGlgI8l4eTsZZox9uUQRbad6upHluEANcrUUBspMAHSak7Khhtwjmb2RFCAaUBj4fJoakeNQePpNMVS488uvxJftgFkEBO1JBQWTdviILFAgoCoxxgsByRq1T0EwMuTZfq7Jnr/Vx/g="
  on:
    tags: true